public enum EffEnum{
	
	NONE,BURN,PARA,FREEZE,POISON,SLEEP,CONFUSION,
	STATATT,STATDEF,STATSPATT,STATSPDEF,STATSPEED,
	STATALL,STATACC,STATEVASION,FLINCH,CRITUP1,CRITUPx2,
	RANDOMWITHDRAW,RECOILTHIRD,RECOILQUARTER,FLIGHT,
	CRASHDAMAGEHALF

};
